# Salesforce Marketing Cloud - Autogenerated SDK

## Overview

The Salesforce Marketing Cloud C# SDK enables developers to easily access the Salesforce Marketing Cloud via the C# platform. 

- This is an upgraded version of the existing community supported [Fuel-CSharp](https://github.com/salesforce-marketingcloud/FuelSDK-CSharp) SDK
- Unlike the [Fuel-CSharp](https://github.com/salesforce-marketingcloud/FuelSDK-CSharp), this SDK is auto generated using [Swagger Codegen](https://github.com/swagger-api/swagger-codegen) and built on top of .Net Standard 2.0

## Supported Features

- [Transactional Messaging](https://developer.salesforce.com/docs/atlas.en-us.mc-apis.meta/mc-apis/transactional-messaging-api.htm)

## Environment Requirements

- .Net Core >= 2.0 (Recommended) 
- .Net Framework >= 4.6.1 (Recommended >= 4.7.2)

## Download

To consume this SDK add the [Salesforce Marketing Cloud SDK](https://www.nuget.org/packages/SalesforceMarketingCloudSDK) to your Project using the following command: 

```Install-Package SalesforceMarketingCloudSDK```

## Getting Started

To find more information on how to consume the SDK, Refer to the [Regression tests](https://github.com/salesforce-marketingcloud/mcsdk-automation-csharp/tree/master/src/Salesforce.MarketingCloud.Test/Api) or the [Code Samples](https://github.com/salesforce-marketingcloud/mcsdk-automation-csharp/tree/master/Samples)

### Note

- Most of the code in this repo is auto generated from the [mcsdk-automation-framework-core](https://github.com/salesforce-marketingcloud/mcsdk-automation-framework-core) and the [mcsdk-automation-framework-csharp](https://github.com/salesforce-marketingcloud/mcsdk-automation-framework-csharp) repos. Other features like authentication flow, caching are directly implemented in this repo.
- If any change is needed in the auto generated code, it has to come from the [mcsdk-automation-framework-core](https://github.com/salesforce-marketingcloud/mcsdk-automation-framework-core) or the [mcsdk-automation-framework-csharp](https://github.com/salesforce-marketingcloud/mcsdk-automation-framework-csharp) repos.
- If any change is needed in the auth flow or caching, it should be done in this repo.

## Contact us

- Request a [new feature](https://github.com/salesforce-marketingcloud/mcsdk-automation-csharp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), add a question or report a bug on GitHub.
- Vote for [Popular Feature Requests](https://github.com/salesforce-marketingcloud/mcsdk-automation-csharp/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) by making relevant comments and add your reaction. Use a reaction in place of a "+1" comment:
    - 👍 - upvote
    - 👎 - downvote

## License
By contributing your code, you agree to license your contribution under the terms of the [BSD 3-Clause License](https://github.com/salesforce-marketingcloud/mcsdk-automation-csharp/blob/master/license.md).
